# Generated by Django 4.0.1 on 2022-03-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappRatingDare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answermodel',
            name='answer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personownchart',
            name='q1',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personownchart',
            name='q10',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personownchart',
            name='q11',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personownchart',
            name='q12',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personownchart',
            name='q13',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personownchart',
            name='q14',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personownchart',
            name='q15',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personownchart',
            name='q16',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personownchart',
            name='q17',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personownchart',
            name='q18',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personownchart',
            name='q19',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personownchart',
            name='q2',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personownchart',
            name='q20',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personownchart',
            name='q3',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personownchart',
            name='q4',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personownchart',
            name='q5',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personownchart',
            name='q6',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personownchart',
            name='q7',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personownchart',
            name='q8',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personownchart',
            name='q9',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=50, null=True),
        ),
    ]
