# Generated by Django 4.0.1 on 2022-03-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappRatingDare', '0002_alter_answermodel_answer_alter_personownchart_q1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personownchart',
            name='q11',
        ),
        migrations.RemoveField(
            model_name='personownchart',
            name='q12',
        ),
        migrations.RemoveField(
            model_name='personownchart',
            name='q13',
        ),
        migrations.RemoveField(
            model_name='personownchart',
            name='q14',
        ),
        migrations.RemoveField(
            model_name='personownchart',
            name='q15',
        ),
        migrations.RemoveField(
            model_name='personownchart',
            name='q16',
        ),
        migrations.RemoveField(
            model_name='personownchart',
            name='q17',
        ),
        migrations.RemoveField(
            model_name='personownchart',
            name='q18',
        ),
        migrations.RemoveField(
            model_name='personownchart',
            name='q19',
        ),
        migrations.RemoveField(
            model_name='personownchart',
            name='q20',
        ),
        migrations.AlterField(
            model_name='personownchart',
            name='q1',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personownchart',
            name='q10',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personownchart',
            name='q2',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personownchart',
            name='q3',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personownchart',
            name='q4',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personownchart',
            name='q5',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personownchart',
            name='q6',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personownchart',
            name='q7',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personownchart',
            name='q8',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personownchart',
            name='q9',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=50, null=True),
        ),
    ]
