# Generated by Django 4.0.1 on 2022-04-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappRatingDare', '0004_answermodel_answer_for_alter_answermodel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answermodel',
            options={'ordering': ('created_time',)},
        ),
        migrations.AlterField(
            model_name='personownchart',
            name='answersChart',
            field=models.ManyToManyField(blank=True, to='whatsappRatingDare.answerModel'),
        ),
    ]
